version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/models:/models
    environment:
      SPOTIPY_REDIRECT_URI: 'http://localhost:8888/callback/'

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000