version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/models:/models

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000